name: release

# 1. QUAND : Uniquement lors de la création d'une étiquette (Tag) officielle
on:
  push:
    tags:
      - "v*"
  workflow_dispatch: # Permet de lancer manuellement depuis l'interface GitHub si besoin

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    # Autorise le bot GitHub à écrire sur la page des Releases
    permissions:
      contents: write 

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # On n'installe plus les outils de dev (pytest), juste les outils d'empaquetage
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build distribution (Création du .whl)
        run: python -m build

      - name: Validate package metadata
        run: python -m twine check dist/*

      # La livraison finale : création de la page de Release sur GitHub
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true